/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Clinic {
    mapLink: string;
    name: string;
    photoImageId?: ImageId;
    address: string;
    phone: string;
}
export interface PatientReview {
    date: bigint;
    reviewText: string;
    patientName: string;
    rating: bigint;
}
export interface AboutSection {
    bioText: string;
    photoImageId?: ImageId;
}
export interface Image {
    id: string;
    data: Uint8Array;
    mimeType: string;
    filename: string;
    uploadedAt: bigint;
}
export interface SocialLink {
    url: string;
    platform: string;
}
export interface Service {
    title: string;
    description: string;
    iconImageId?: ImageId;
}
export interface MedicalPracticeContent {
    clinics: Array<Clinic>;
    aboutSection?: AboutSection;
    heroSection?: HeroSection;
    socialLinks: Array<SocialLink>;
    patientReviews: Array<PatientReview>;
    services: Array<Service>;
    footer?: DetailedFooter;
}
export interface HeroSection {
    tagline: string;
    backgroundImageId?: ImageId;
    headline: string;
    subheadline: string;
}
export interface DetailedFooter {
    tagline: string;
    copyrightText: string;
    practiceName: string;
    shortDescription: string;
    address: string;
    openingHours: string;
    contactEmail: string;
    phone: string;
}
export type ImageId = string;
export interface UserProfile {
    name: string;
    email?: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addClinic(name: string, address: string, phone: string, mapLink: string, photoImageId: ImageId | null): Promise<void>;
    addPatientReview(patientName: string, reviewText: string, rating: bigint, date: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createService(title: string, description: string, iconImageId: ImageId | null): Promise<void>;
    deleteImage(id: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContent(): Promise<MedicalPracticeContent>;
    getImage(id: string): Promise<Image | null>;
    getSiteTheme(): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listImages(): Promise<Array<Image>>;
    login(username: string, password: string): Promise<string | null>;
    logout(token: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAboutSection(section: AboutSection): Promise<void>;
    setClinics(clinics: Array<Clinic>): Promise<void>;
    setFooter(footer: DetailedFooter): Promise<void>;
    setHeroSection(section: HeroSection): Promise<void>;
    setPatientReviews(reviews: Array<PatientReview>): Promise<void>;
    setServices(services: Array<Service>): Promise<void>;
    setSiteTheme(themeName: string): Promise<void>;
    setSocialLinks(links: Array<SocialLink>): Promise<void>;
    uploadImage(filename: string, mimeType: string, data: Uint8Array): Promise<ImageId>;
    validateToken(token: string): Promise<boolean>;
}
import type { AboutSection as _AboutSection, Clinic as _Clinic, DetailedFooter as _DetailedFooter, HeroSection as _HeroSection, Image as _Image, ImageId as _ImageId, MedicalPracticeContent as _MedicalPracticeContent, PatientReview as _PatientReview, Service as _Service, SocialLink as _SocialLink, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addClinic(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ImageId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addClinic(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClinic(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addPatientReview(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPatientReview(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPatientReview(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createService(arg0: string, arg1: string, arg2: ImageId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createService(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteImage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteImage(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContent(): Promise<MedicalPracticeContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getContent();
                return from_candid_MedicalPracticeContent_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContent();
            return from_candid_MedicalPracticeContent_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImage(arg0: string): Promise<Image | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getImage(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImage(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteTheme(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteTheme();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteTheme();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listImages(): Promise<Array<Image>> {
        if (this.processError) {
            try {
                const result = await this.actor.listImages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listImages();
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setAboutSection(arg0: AboutSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAboutSection(to_candid_AboutSection_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAboutSection(to_candid_AboutSection_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setClinics(arg0: Array<Clinic>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setClinics(to_candid_vec_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setClinics(to_candid_vec_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setFooter(arg0: DetailedFooter): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFooter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFooter(arg0);
            return result;
        }
    }
    async setHeroSection(arg0: HeroSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setHeroSection(to_candid_HeroSection_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHeroSection(to_candid_HeroSection_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setPatientReviews(arg0: Array<PatientReview>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPatientReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPatientReviews(arg0);
            return result;
        }
    }
    async setServices(arg0: Array<Service>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setServices(to_candid_vec_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setServices(to_candid_vec_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setSiteTheme(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSiteTheme(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSiteTheme(arg0);
            return result;
        }
    }
    async setSocialLinks(arg0: Array<SocialLink>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSocialLinks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSocialLinks(arg0);
            return result;
        }
    }
    async uploadImage(arg0: string, arg1: string, arg2: Uint8Array): Promise<ImageId> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadImage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadImage(arg0, arg1, arg2);
            return result;
        }
    }
    async validateToken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateToken(arg0);
            return result;
        }
    }
}
function from_candid_AboutSection_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AboutSection): AboutSection {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Clinic_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Clinic): Clinic {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_HeroSection_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeroSection): HeroSection {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_MedicalPracticeContent_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MedicalPracticeContent): MedicalPracticeContent {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ImageId]): ImageId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AboutSection]): AboutSection | null {
    return value.length === 0 ? null : from_candid_AboutSection_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HeroSection]): HeroSection | null {
    return value.length === 0 ? null : from_candid_HeroSection_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DetailedFooter]): DetailedFooter | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Image]): Image | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clinics: Array<_Clinic>;
    aboutSection: [] | [_AboutSection];
    heroSection: [] | [_HeroSection];
    socialLinks: Array<_SocialLink>;
    patientReviews: Array<_PatientReview>;
    services: Array<_Service>;
    footer: [] | [_DetailedFooter];
}): {
    clinics: Array<Clinic>;
    aboutSection?: AboutSection;
    heroSection?: HeroSection;
    socialLinks: Array<SocialLink>;
    patientReviews: Array<PatientReview>;
    services: Array<Service>;
    footer?: DetailedFooter;
} {
    return {
        clinics: from_candid_vec_n12(_uploadFile, _downloadFile, value.clinics),
        aboutSection: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.aboutSection)),
        heroSection: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.heroSection)),
        socialLinks: value.socialLinks,
        patientReviews: value.patientReviews,
        services: from_candid_vec_n22(_uploadFile, _downloadFile, value.services),
        footer: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.footer))
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mapLink: string;
    name: string;
    photoImageId: [] | [_ImageId];
    address: string;
    phone: string;
}): {
    mapLink: string;
    name: string;
    photoImageId?: ImageId;
    address: string;
    phone: string;
} {
    return {
        mapLink: value.mapLink,
        name: value.name,
        photoImageId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.photoImageId)),
        address: value.address,
        phone: value.phone
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bioText: string;
    photoImageId: [] | [_ImageId];
}): {
    bioText: string;
    photoImageId?: ImageId;
} {
    return {
        bioText: value.bioText,
        photoImageId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.photoImageId))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tagline: string;
    backgroundImageId: [] | [_ImageId];
    headline: string;
    subheadline: string;
}): {
    tagline: string;
    backgroundImageId?: ImageId;
    headline: string;
    subheadline: string;
} {
    return {
        tagline: value.tagline,
        backgroundImageId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.backgroundImageId)),
        headline: value.headline,
        subheadline: value.subheadline
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    iconImageId: [] | [_ImageId];
}): {
    title: string;
    description: string;
    iconImageId?: ImageId;
} {
    return {
        title: value.title,
        description: value.description,
        iconImageId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.iconImageId))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
}): {
    name: string;
    email?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Clinic>): Array<Clinic> {
    return value.map((x)=>from_candid_Clinic_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n23(_uploadFile, _downloadFile, x));
}
function to_candid_AboutSection_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AboutSection): _AboutSection {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_Clinic_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Clinic): _Clinic {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_HeroSection_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HeroSection): _HeroSection {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_Service_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): _Service {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImageId | null): [] | [_ImageId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
}): {
    name: string;
    email: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bioText: string;
    photoImageId?: ImageId;
}): {
    bioText: string;
    photoImageId: [] | [_ImageId];
} {
    return {
        bioText: value.bioText,
        photoImageId: value.photoImageId ? candid_some(value.photoImageId) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mapLink: string;
    name: string;
    photoImageId?: ImageId;
    address: string;
    phone: string;
}): {
    mapLink: string;
    name: string;
    photoImageId: [] | [_ImageId];
    address: string;
    phone: string;
} {
    return {
        mapLink: value.mapLink,
        name: value.name,
        photoImageId: value.photoImageId ? candid_some(value.photoImageId) : candid_none(),
        address: value.address,
        phone: value.phone
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tagline: string;
    backgroundImageId?: ImageId;
    headline: string;
    subheadline: string;
}): {
    tagline: string;
    backgroundImageId: [] | [_ImageId];
    headline: string;
    subheadline: string;
} {
    return {
        tagline: value.tagline,
        backgroundImageId: value.backgroundImageId ? candid_some(value.backgroundImageId) : candid_none(),
        headline: value.headline,
        subheadline: value.subheadline
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    iconImageId?: ImageId;
}): {
    title: string;
    description: string;
    iconImageId: [] | [_ImageId];
} {
    return {
        title: value.title,
        description: value.description,
        iconImageId: value.iconImageId ? candid_some(value.iconImageId) : candid_none()
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Clinic>): Array<_Clinic> {
    return value.map((x)=>to_candid_Clinic_n32(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Service>): Array<_Service> {
    return value.map((x)=>to_candid_Service_n37(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
