/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ImageId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const Clinic = IDL.Record({
  'mapLink' : IDL.Text,
  'name' : IDL.Text,
  'photoImageId' : IDL.Opt(ImageId),
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const AboutSection = IDL.Record({
  'bioText' : IDL.Text,
  'photoImageId' : IDL.Opt(ImageId),
});
export const HeroSection = IDL.Record({
  'tagline' : IDL.Text,
  'backgroundImageId' : IDL.Opt(ImageId),
  'headline' : IDL.Text,
  'subheadline' : IDL.Text,
});
export const SocialLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const PatientReview = IDL.Record({
  'date' : IDL.Int,
  'reviewText' : IDL.Text,
  'patientName' : IDL.Text,
  'rating' : IDL.Int,
});
export const Service = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'iconImageId' : IDL.Opt(ImageId),
});
export const DetailedFooter = IDL.Record({
  'tagline' : IDL.Text,
  'copyrightText' : IDL.Text,
  'practiceName' : IDL.Text,
  'shortDescription' : IDL.Text,
  'address' : IDL.Text,
  'openingHours' : IDL.Text,
  'contactEmail' : IDL.Text,
  'phone' : IDL.Text,
});
export const MedicalPracticeContent = IDL.Record({
  'clinics' : IDL.Vec(Clinic),
  'aboutSection' : IDL.Opt(AboutSection),
  'heroSection' : IDL.Opt(HeroSection),
  'socialLinks' : IDL.Vec(SocialLink),
  'patientReviews' : IDL.Vec(PatientReview),
  'services' : IDL.Vec(Service),
  'footer' : IDL.Opt(DetailedFooter),
});
export const Image = IDL.Record({
  'id' : IDL.Text,
  'data' : IDL.Vec(IDL.Nat8),
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
  'uploadedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClinic' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ImageId)],
      [],
      [],
    ),
  'addPatientReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Int, IDL.Int], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createService' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ImageId)], [], []),
  'deleteImage' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContent' : IDL.Func([], [MedicalPracticeContent], ['query']),
  'getImage' : IDL.Func([IDL.Text], [IDL.Opt(Image)], ['query']),
  'getSiteTheme' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listImages' : IDL.Func([], [IDL.Vec(Image)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAboutSection' : IDL.Func([AboutSection], [], []),
  'setClinics' : IDL.Func([IDL.Vec(Clinic)], [], []),
  'setFooter' : IDL.Func([DetailedFooter], [], []),
  'setHeroSection' : IDL.Func([HeroSection], [], []),
  'setPatientReviews' : IDL.Func([IDL.Vec(PatientReview)], [], []),
  'setServices' : IDL.Func([IDL.Vec(Service)], [], []),
  'setSiteTheme' : IDL.Func([IDL.Text], [], []),
  'setSocialLinks' : IDL.Func([IDL.Vec(SocialLink)], [], []),
  'uploadImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [ImageId],
      [],
    ),
  'validateToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ImageId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const Clinic = IDL.Record({
    'mapLink' : IDL.Text,
    'name' : IDL.Text,
    'photoImageId' : IDL.Opt(ImageId),
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AboutSection = IDL.Record({
    'bioText' : IDL.Text,
    'photoImageId' : IDL.Opt(ImageId),
  });
  const HeroSection = IDL.Record({
    'tagline' : IDL.Text,
    'backgroundImageId' : IDL.Opt(ImageId),
    'headline' : IDL.Text,
    'subheadline' : IDL.Text,
  });
  const SocialLink = IDL.Record({ 'url' : IDL.Text, 'platform' : IDL.Text });
  const PatientReview = IDL.Record({
    'date' : IDL.Int,
    'reviewText' : IDL.Text,
    'patientName' : IDL.Text,
    'rating' : IDL.Int,
  });
  const Service = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'iconImageId' : IDL.Opt(ImageId),
  });
  const DetailedFooter = IDL.Record({
    'tagline' : IDL.Text,
    'copyrightText' : IDL.Text,
    'practiceName' : IDL.Text,
    'shortDescription' : IDL.Text,
    'address' : IDL.Text,
    'openingHours' : IDL.Text,
    'contactEmail' : IDL.Text,
    'phone' : IDL.Text,
  });
  const MedicalPracticeContent = IDL.Record({
    'clinics' : IDL.Vec(Clinic),
    'aboutSection' : IDL.Opt(AboutSection),
    'heroSection' : IDL.Opt(HeroSection),
    'socialLinks' : IDL.Vec(SocialLink),
    'patientReviews' : IDL.Vec(PatientReview),
    'services' : IDL.Vec(Service),
    'footer' : IDL.Opt(DetailedFooter),
  });
  const Image = IDL.Record({
    'id' : IDL.Text,
    'data' : IDL.Vec(IDL.Nat8),
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClinic' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ImageId)],
        [],
        [],
      ),
    'addPatientReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Int],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createService' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ImageId)], [], []),
    'deleteImage' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContent' : IDL.Func([], [MedicalPracticeContent], ['query']),
    'getImage' : IDL.Func([IDL.Text], [IDL.Opt(Image)], ['query']),
    'getSiteTheme' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listImages' : IDL.Func([], [IDL.Vec(Image)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAboutSection' : IDL.Func([AboutSection], [], []),
    'setClinics' : IDL.Func([IDL.Vec(Clinic)], [], []),
    'setFooter' : IDL.Func([DetailedFooter], [], []),
    'setHeroSection' : IDL.Func([HeroSection], [], []),
    'setPatientReviews' : IDL.Func([IDL.Vec(PatientReview)], [], []),
    'setServices' : IDL.Func([IDL.Vec(Service)], [], []),
    'setSiteTheme' : IDL.Func([IDL.Text], [], []),
    'setSocialLinks' : IDL.Func([IDL.Vec(SocialLink)], [], []),
    'uploadImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [ImageId],
        [],
      ),
    'validateToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };