/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutSection {
  'bioText' : string,
  'photoImageId' : [] | [ImageId],
}
export interface Clinic {
  'mapLink' : string,
  'name' : string,
  'photoImageId' : [] | [ImageId],
  'address' : string,
  'phone' : string,
}
export interface DetailedFooter {
  'tagline' : string,
  'copyrightText' : string,
  'practiceName' : string,
  'shortDescription' : string,
  'address' : string,
  'openingHours' : string,
  'contactEmail' : string,
  'phone' : string,
}
export interface HeroSection {
  'tagline' : string,
  'backgroundImageId' : [] | [ImageId],
  'headline' : string,
  'subheadline' : string,
}
export interface Image {
  'id' : string,
  'data' : Uint8Array,
  'mimeType' : string,
  'filename' : string,
  'uploadedAt' : bigint,
}
export type ImageId = string;
export interface MedicalPracticeContent {
  'clinics' : Array<Clinic>,
  'aboutSection' : [] | [AboutSection],
  'heroSection' : [] | [HeroSection],
  'socialLinks' : Array<SocialLink>,
  'patientReviews' : Array<PatientReview>,
  'services' : Array<Service>,
  'footer' : [] | [DetailedFooter],
}
export interface PatientReview {
  'date' : bigint,
  'reviewText' : string,
  'patientName' : string,
  'rating' : bigint,
}
export interface Service {
  'title' : string,
  'description' : string,
  'iconImageId' : [] | [ImageId],
}
export interface SocialLink { 'url' : string, 'platform' : string }
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClinic' : ActorMethod<
    [string, string, string, string, [] | [ImageId]],
    undefined
  >,
  'addPatientReview' : ActorMethod<[string, string, bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createService' : ActorMethod<[string, string, [] | [ImageId]], undefined>,
  'deleteImage' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContent' : ActorMethod<[], MedicalPracticeContent>,
  'getImage' : ActorMethod<[string], [] | [Image]>,
  'getSiteTheme' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listImages' : ActorMethod<[], Array<Image>>,
  'login' : ActorMethod<[string, string], [] | [string]>,
  'logout' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAboutSection' : ActorMethod<[AboutSection], undefined>,
  'setClinics' : ActorMethod<[Array<Clinic>], undefined>,
  'setFooter' : ActorMethod<[DetailedFooter], undefined>,
  'setHeroSection' : ActorMethod<[HeroSection], undefined>,
  'setPatientReviews' : ActorMethod<[Array<PatientReview>], undefined>,
  'setServices' : ActorMethod<[Array<Service>], undefined>,
  'setSiteTheme' : ActorMethod<[string], undefined>,
  'setSocialLinks' : ActorMethod<[Array<SocialLink>], undefined>,
  'uploadImage' : ActorMethod<[string, string, Uint8Array], ImageId>,
  'validateToken' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];